// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetoTecnico.Infrastructure.Persistence;

#nullable disable

namespace RetoTecnico.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507044038_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RetoTecnico.Domain.Entities.EvaluacionImc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AlturaCentimetros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionResultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PesoKilogramos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorImc")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("Id");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("RetoTecnico.Domain.Entities.RangoImc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorMaximo")
                        .HasColumnType("decimal(18,1)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("decimal(18,1)");

                    b.HasKey("Id");

                    b.ToTable("RangosImc");
                });
#pragma warning restore 612, 618
        }
    }
}
